### ISSUE TITLE
not working in idle

### ISSUE THREAD

**Issue by uttaravallivinod** [sprksh/finance-calculator#1]
while using package by importing with name like "import finance_calculator as fc"

it shows below error 

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import finance_calculator as fc
  File "C:\Users\91767\AppData\Local\Programs\Python\Python38-32\lib\site-packages\finance_calculator\__init__.py", line 2, in <module>
    from .api import (
  File "C:\Users\91767\AppData\Local\Programs\Python\Python38-32\lib\site-packages\finance_calculator\api.py", line 2, in <module>
    from src.finance_calculator.calculators.portfolio_calculator import XIRR
ModuleNotFoundError: No module named 'src'

**Comment by sprksh** [comment]
Hey, I have released a newer version. Can you check now.
